<?xml version="1.0" encoding="UTF-8"?><testrun name="CalculadoraJunitTest" project="QualidadeTesteSoftware" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="Calculadora.CalculadoraJunitTest" time="0.044" displayname="CalculadoraJunitTest" uniqueid="[engine:junit-jupiter]/[class:Calculadora.CalculadoraJunitTest]">
    <testcase name="DividirDoisValoresSendoPrimeiroZero" classname="Calculadora.CalculadoraJunitTest" time="0.044" displayname="DividirDoisValoresSendoPrimeiroZero()" uniqueid="[engine:junit-jupiter]/[class:Calculadora.CalculadoraJunitTest]/[method:DividirDoisValoresSendoPrimeiroZero()]">
      <failure>junit.framework.AssertionFailedError: expected:&lt;5&gt; but was:&lt;0&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at Calculadora.CalculadoraJunitTest.DividirDoisValoresSendoPrimeiroZero(CalculadoraJunitTest.java:103)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
